version: '3.8'

services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "5001:5000"

  db:
    image: postgres:13.0-alpine
    container_name: 'db_api-store'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data: