version: '3.8'

services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "5001:5000"

  db:
    image: postgres:13.0-alpine
    container_name: 'db_api-store'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    container_name: 'redis-flask'
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    # command: redis-server --requirepass redis2022 --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  postgres_data:
  redis_data: